apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polling-app
  template:
    metadata:
      labels:
        app: polling-app
    spec:
      containers:
      - name: polling-app
        image: your-polling-app-image:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_PORT
          value: "80"
