apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: 6c4aacdc-885b-40dd-9c97-364d45186f14   
    keyvaultName: mysecretkey        
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: myysecretkey             
          objectType: secret             
          objectVersion: ""               
    tenantId: e77151a5-ccca-4f94-91c3-8899653de95d                 