apiVersion: v1
kind: Service
metadata:
  name: smiley-service
spec:
  selector:
    app: smiley-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: smiley-app
spec:
  containers:
  - name: smiley-container
    image: nginx:latest
    ports:
    - containerPort: 80
  restartPolicy: Always
